apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: us.gcr.io/mlxlabs-io/k8s-agent
    # - image: k8s_agent_image
      context: .
      sync:
        infer:
          - k8s_agent/**
      docker:
        dockerfile: Dockerfile
manifests:
  helm:
    releases:
      - name: k8s-agent
        chartPath: ./deployment/helm/k8s-agent
        valuesFiles:
          - dev-values.yaml
        setValues:
          command: watchmedo
          args:
            - auto-restart
            - --directory=/src
            - --pattern=*.py
            - --recursive
            - --
            - python
            - -m
            - k8s_agent
        setValueTemplates:
          image: "{{ .IMAGE_FULLY_QUALIFIED_us_gcr_io_mlxlabs_io_k8s_agent }}"
        skipBuildDependencies: true
# deploy:
#   helm:
#     releases:
#       - name: mlxlabs
#         chartPath: ./deployment/helm/backend
#         valuesFiles:
#           - dev-values.yaml
#           - dev-secrets.yaml
#         skipBuildDependencies: true
