{{- if and .Values.workloadType (or .Values.envVars .Values.global.envVars .Values.files .Values.global.files) }}
  {{- $envVars := deepCopy .Values.envVars | mergeOverwrite (deepCopy .Values.global.envVars) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-agent.fullname" . }}
  labels:
    {{- include "k8s-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := $envVars }}
    {{- if $val }}
  {{ $key }}: {{ printf "%v" $val | b64enc | quote }}
    {{- end }}
  {{- end }}
  {{- $files := deepCopy .Values.files | mergeOverwrite (deepCopy .Values.global.files) -}}
  {{- $root := . -}}
  {{- range $path, $data := $files }}
    {{- if $data }}
      {{- if not (contains "/" $path) }}
        {{ fail (printf "File paths \"%s\" must be a full absolute path" $path) }}
      {{- else }}
  {{ trimPrefix "/" $path | replace "/" "-" | replace "." "-" | quote }}: {{  printf "%v" $data | b64enc | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
