{{- if or .Values.global.serviceAccount.create .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "k8s-agent.serviceAccountName" . }}
  {{- with (coalesce .Values.serviceAccount.annotations .Values.global.serviceAccount.annotations) }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "k8s-agent.labels" . | nindent 4 }}
  {{- with (coalesce .Values.serviceAccount.imagePullSecrets .Values.global.serviceAccount.imagePullSecrets) }}
imagePullSecrets:
    {{- range . }}
  - name: {{ . }}
    {{- end }}
  {{- end }}
{{- end -}}
