apiVersion: v2
name: k8s-agent
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: redis-stack-server
    version: ">=0.4.8"
    repository: https://redis-stack.github.io/helm-redis-stack/