###
# ```{rubric} Deploy Docs GHA
# ```
# ---
# GitHub Actions configuration to deploy pages.
#
# ```{literalinclude} ../.github/workflows/docs.yml
# :language: yaml
# :caption: .github/workflows/docs.yml
# :start-at: "name: Deploy Docs\n"
# :end-before: "  ###\n"
# ```
name: Deploy Docs
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
permissions:
    contents: read
    issues: read
    checks: write
    pull-requests: write

###
# ```{rubric} Jobs
# ```
# ---
# Define jobs to deploy to pages.
jobs:
  ###
  # ```{rubric} Build Pages
  # ```
  # ---
  # Build pages site and upload an artifact
  #
  # ```{literalinclude} ../.github/workflows/docs.yml
  # :language: yaml
  # :start-at: "  build:\n"
  # :end-before: "  ###\n"
  # ```
  build:
    runs-on: ubuntu-20.04
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: 3.11
          cache: pipenv
      - name: Setup pages
        uses: actions/configure-pages@main
      - name: Build the site
        run: |
          set -x
          cd docs
          pip install -U pip pipenv
          pipenv install
          pipenv run sphinx-build . ./deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: './docs/deploy'
  ###
  # ```{rubric} Deploy Pages
  # ```
  # ---
  # Download the artifact and deploy to pages.
  #
  # ```{literalinclude} ../.github/workflows/docs.yml
  # :language: yaml
  # :start-at: "  pages:\n"
  # ```
  pages:
    needs: build
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download pages artifact
        id: download
        uses: actions/download-artifact@main
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
